# TCL File Generated by Component Editor 12.1sp1
# Tue Jun 25 23:07:40 CST 2013
# DO NOT MODIFY


# 
# mse "mse" v1.0
# zhizhou li 2013.06.25.23:07:40
# mse 8bit host
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module mse
# 
set_module_property DESCRIPTION "mse 8bit host"
set_module_property NAME mse
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "zhizhou li"
set_module_property DISPLAY_NAME mse
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mse_host
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file mse_host.v VERILOG PATH qsys_root/mse_host.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file mse_host.v VERILOG PATH qsys_root/qsys_root/mse_host.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point mrst
# 
add_interface mrst reset start
set_interface_property mrst associatedClock mclk
set_interface_property mrst associatedDirectReset mrst
set_interface_property mrst associatedResetSinks ""
set_interface_property mrst synchronousEdges DEASSERT
set_interface_property mrst ENABLED true

add_interface_port mrst rso_MRST_reset reset Output 1


# 
# connection point mclk
# 
add_interface mclk clock start
set_interface_property mclk associatedDirectClock mclk
set_interface_property mclk clockRate 0
set_interface_property mclk clockRateKnown false
set_interface_property mclk ENABLED true

add_interface_port mclk cso_MCLK_clk clk Output 1


# 
# connection point m1
# 
add_interface m1 avalon start
set_interface_property m1 addressUnits SYMBOLS
set_interface_property m1 associatedClock mclk
set_interface_property m1 associatedReset mrst
set_interface_property m1 bitsPerSymbol 8
set_interface_property m1 burstOnBurstBoundariesOnly false
set_interface_property m1 burstcountUnits WORDS
set_interface_property m1 doStreamReads false
set_interface_property m1 doStreamWrites false
set_interface_property m1 holdTime 0
set_interface_property m1 linewrapBursts false
set_interface_property m1 maximumPendingReadTransactions 0
set_interface_property m1 readLatency 0
set_interface_property m1 readWaitTime 1
set_interface_property m1 setupTime 0
set_interface_property m1 timingUnits Cycles
set_interface_property m1 writeWaitTime 0
set_interface_property m1 ENABLED true

add_interface_port m1 avm_M1_writedata writedata Output 32
add_interface_port m1 avm_M1_readdata readdata Input 32
add_interface_port m1 avm_M1_address address Output 8
add_interface_port m1 avm_M1_byteenable byteenable Output 4
add_interface_port m1 avm_M1_write write Output 1
add_interface_port m1 avm_M1_read read Output 1
add_interface_port m1 avm_M1_begintransfer begintransfer Output 1
add_interface_port m1 avm_M1_readdatavalid readdatavalid Input 1
add_interface_port m1 avm_M1_waitrequest waitrequest Input 1


# 
# connection point mse
# 
add_interface mse conduit end
set_interface_property mse associatedClock mclk
set_interface_property mse associatedReset mrst
set_interface_property mse ENABLED true

add_interface_port mse coe_M1_RSTN export Input 1
add_interface_port mse coe_M1_CLK export Input 1
add_interface_port mse coe_M1_ADDR export Input 8
add_interface_port mse coe_M1_DATA export Bidir 8
add_interface_port mse coe_M1_RDN export Input 1
add_interface_port mse coe_M1_WRN export Input 1
add_interface_port mse coe_M1_WAITN export Output 1

